site_name: ADLINK Neuron Documents
pages:
  - Introduction: index.md
  - Neuron SEMA User Guide:
    - SEMA GPIO: sema/sema-gpio.md
  - Neuron DDSBot: neuron-ddsbot.md
  - Neuron NeuronBot: neuron-neuronbot.md
  - Neuron OmniBot: neuron-omnibot.md
theme:
  name: material
  custom_dir: 'theme/'
  logo: 'img/neuron_logo.'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/Adlink-ROS'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCscUHwoBilWqTBkN0KNoEkQ/videos'
